### ISSUE TITLE
Troubleshooting Zero Downtime Deployment for Unicorn

### ISSUE THREAD

**Issue by ziazek** [TalkingQuickly/capistrano-3-rails-template#35]
I've tried solving this to no avail so far. I think I've followed the instructions in your book correctly to this point.

1) When I do `$ bundle exec cap production deploy:restart` , it fails:
```
DEBUG [64c2c32d] Running /usr/bin/env [ -d /usr/local/rbenv/versions/2.1.5 ] as deploy@(example).com
DEBUG [64c2c32d] Command: [ -d /usr/local/rbenv/versions/2.1.5 ]
DEBUG [64c2c32d] Finished in 1.087 seconds with exit status 0 (successful).
INFO [fb0a4d08] Running /usr/bin/env sudo /etc/init.d/unicorn_ffth_a2_production restart as deploy@(example).com
DEBUG [fb0a4d08] Command: ( RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.1.5 /usr/bin/env sudo /etc/init.d/unicorn_ffth_a2_production restart )
DEBUG [fb0a4d08] 	reloaded OK
INFO [fb0a4d08] Finished in 0.032 seconds with exit status 0 (successful).
INFO [131af9e6] Running /usr/bin/env sudo /etc/init.d/unicorn_ffth_a2_production restart as deploy@(example).com
DEBUG [131af9e6] Command: ( RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.1.5 /usr/bin/env sudo /etc/init.d/unicorn_ffth_a2_production restart )
DEBUG [131af9e6] 	Couldn't reload, starting 'cd /home/deploy/apps/ffth_a2_production/current;  bundle exec unicorn -D -c /home/deploy/apps/ffth_a2_production/shared/config/unicorn.rb -E production' instead
DEBUG [131af9e6] 	master failed to start, check stderr log for details
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@(example).com: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: Couldn't reload, starting 'cd /home/deploy/apps/ffth_a2_production/current;  bundle exec unicorn -D -c /home/deploy/apps/ffth_a2_production/shared/config/unicorn.rb -E production' instead
master failed to start, check stderr log for details
...
```

2) When I check the website, the changes are actually successfully deployed when I do a full `cap deploy`, but Capistrano does not continue after the exception is thrown.

3) I ssh'd in as the `deploy` user and ran `$ sudo service unicorn_ffth_a2_production restart` and got
``` 
reloaded OK
```

4) I checked the logs. When I run **step 1**, the output is 
```
I, [2015-02-03T04:05:41.420675 #3975]  INFO -- : executing ["/home/deploy/apps/ffth_a2_production/shared/bundle/ruby/2.1.0/bin/unicorn", "-D", "-c", "/home/deploy/apps/ffth_a2_production/shared/config/unicorn.rb", "-E", "production", {10=>#<Kgio::UNIXServer:/tmp/unicorn.ffth_a2_production.sock>}] (in /home/deploy/apps/ffth_a2_production/releases/20150203081053)
I, [2015-02-03T04:05:42.056269 #3975]  INFO -- : inherited addr=/tmp/unicorn.ffth_a2_production.sock fd=10
I, [2015-02-03T04:05:42.059709 #3975]  INFO -- : Refreshing Gem list
/home/deploy/apps/ffth_a2_production/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:206:in `pid=': Already running on PID:3975 (or pid=/home/deploy/apps/ffth_a2_production/current/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/deploy/apps/ffth_a2_production/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:135:in `start'
	from /home/deploy/apps/ffth_a2_production/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
	from /home/deploy/apps/ffth_a2_production/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
	from /home/deploy/apps/ffth_a2_production/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
We've got an old pid and server pid is not the old pid
killing master process (good thing tm)
We've got an old pid and server pid is not the old pid
killing master process (good thing tm)
We've got an old pid and server pid is not the old pid
killing master process (good thing tm)
I, [2015-02-03T04:05:44.192262 #3975]  INFO -- : master process ready
I, [2015-02-03T04:05:44.206371 #4067]  INFO -- : worker=1 ready
I, [2015-02-03T04:05:44.208465 #4063]  INFO -- : worker=0 ready
I, [2015-02-03T04:05:44.221720 #4071]  INFO -- : worker=2 ready
I, [2015-02-03T04:05:44.452826 #3740]  INFO -- : reaped #<Process::Status: pid 3752 exit 0> worker=2
I, [2015-02-03T04:05:44.453221 #3740]  INFO -- : reaped #<Process::Status: pid 3760 exit 0> worker=0
I, [2015-02-03T04:05:44.553920 #3740]  INFO -- : reaped #<Process::Status: pid 3748 exit 0> worker=1
I, [2015-02-03T04:05:44.554506 #3740]  INFO -- : master complete
```
(the workers do restart)

5) The logs show no error when I run **step 3**.

I've tried restarting nginx and rebooting Ubuntu, didn't work.

Any advice would be greatly appreciated. Thanks!

**Comment by ziazek** [comment]
It turns out I had both `require 'capistrano/cookbook'` and the lib/capistrano/tasks folder, and the same task was repeated twice. Commenting out the require solved the issue.
